name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      HEROKU_PIPELINE_ID: ${{secrets.HEROKU_PIPELINE_ID}}
      HEROKU_PIPELINE_COUPLING_STAGE: review

    steps:
    - name: Set outputs
      id: vars
      run: echo "::set-output name=datetime::"`date "+%Y%m%d%H%M%S"`

    - name: echo1
      run: echo ${{ steps.vars.outputs.datetime }}

    - uses: actions/checkout@v2

    - name: sleep
      run: sleep 10

    - name: echo2
      run: echo ${{ steps.vars.outputs.datetime }}

    - name: Set HEROKU review-apps config
      run: curl -s -n -X PATCH "https://api.heroku.com/pipelines/${{ env.HEROKU_PIPELINE_ID }}/stage/${{ env.HEROKU_PIPELINE_COUPLING_STAGE }}/config-vars" -d '{"SCRATCH_RELEASE_VERSION":"${{ steps.vars.outputs.datetime }}"}' -H "Content-Type:application/json" -H "Accept:application/vnd.heroku+json; version=3" -H "Authorization:Bearer ${{ secrets.HEROKU_API_KEY }}"

