name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME_PROD }}
      HEROKU_PIPELINE_NAME: ssk-helloworld-pipe

    steps:
    - name: Set outputs
      id: vars
      run: echo "::set-output name=datetime::"`date "+%Y%m%d%H%M%S"`

    - name: echo1
      run: echo ${{ steps.vars.outputs.datetime }}

    - uses: actions/checkout@v2

    - name: sleep
      run: sleep 10

    - name: echo2
      run: echo ${{ steps.vars.outputs.datetime }}

    - name: echo3
      run: echo ${{ env.HEROKU_APP_NAME }}

    - name: HEROKU config
      uses: "actions/heroku@master"
      with:
        args: config:set HELLO=GOODBYE -p ${{ env.HEROKU_PIPELINE_NAME }}
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      #  HEROKU_APP: env.HEROKU_APP_NAME

